service: sls-example
provider:
  name: aws
  runtime: nodejs14.x
  stage: ${self:custom.stage}
  region: ap-northeast-1
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  environment:
    memcachedEndpoint:
      "Fn::Join": [":", ["Fn::GetAtt": [ServerlessElasticacheCluster, ConfigurationEndpoint.Address], "Fn::GetAtt": [ServerlessElasticacheCluster, ConfigurationEndpoint.Port]]]
    postgresEndpoint:
      "Fn::Join": [":", ["Fn::GetAtt": [ServerlessRDSCluster, Endpoint.Address], "Fn::GetAtt": [ServerlessRDSCluster, Endpoint.Port]]]
    databasedbname: "managed"
    username: "cell"
    password: "cellpj123"

custom:
  bucketName: sls-example-${self:custom.stage}
  defaultEnvironmentGroup: dev
  stage: ${opt:stage, self:custom.defaultEnvironmentGroup}
  s3Sync:
    - bucketName: sls-example-${self:custom.stage}
      localDir: public
      params:
        - '**/*.html':
            CacheControl: 'no-store'
        - '**/*.json':
            CacheControl: 'public, max-age=2592000, immutable'
        - '**/*.js':
            CacheControl: 'public, max-age=2592000, immutable'
        - '**/*.css':
            CacheControl: 'public, max-age=2592000, immutable'
        - '**/*.webmanifest':
            CacheControl: 'public, max-age=2592000, immutable'
        - '**/*.map':
            CacheControl: 'public, max-age=2592000, immutable'
        - '**/*.ico':
            CacheControl: 'public, max-age=2592000, immutable'
        - 'assets/**':
            CacheControl: 'public, max-age=2592000, immutable'
plugins:
  - serverless-s3-sync
package:
  artifact: target/serverless-springboot2-example-1.0-SNAPSHOT-lambda-package.zip
functions:
  serverlessTest:
    handler: com.amazonaws.serverless.sample.springboot2.StreamLambdaHandler
    runtime: java8
    vpc:
      securityGroupIds:
        - "Fn::GetAtt": ServerlessSecurityGroup.GroupId
      subnetIds:
        - Ref: ServerlessSubnetA
        - Ref: ServerlessSubnetC
    events:
      - http:
          path: /pets
          method: ANY
          response:
            headers:
              Content-Type: "'application/json'"
      - http:
          path: /pets/{proxy+}
          method: ANY
          response:
            headers:
              Content-Type: "'application/json'"
resources:
  - ${file(/RdsProxyResources.yml)}
  Resources:
    DefaultCachePolicy:
      Type: 'AWS::CloudFront::CachePolicy'
      Properties:
        CachePolicyConfig:
          DefaultTTL: 86400
          MaxTTL: 31536000
          MinTTL: 1
          Name: sls-cache-${self:custom.stage}
          ParametersInCacheKeyAndForwardedToOrigin:
            CookiesConfig:
              CookieBehavior: 'none'
            EnableAcceptEncodingBrotli: true
            EnableAcceptEncodingGzip: true
            HeadersConfig:
              HeaderBehavior: 'none'
            QueryStringsConfig:
              QueryStringBehavior: 'none'
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          HttpVersion: http2
          PriceClass: PriceClass_200
          DefaultRootObject: index.html
          CacheBehaviors:
            - PathPattern: /pets*
              TargetOriginId: apiGatewayOrigin-${self:custom.stage}
              AllowedMethods:
                - GET
                - HEAD
                - OPTIONS
                - PUT
                - POST
                - PATCH
                - DELETE
              CachedMethods:
                - HEAD
                - GET
              Compress: true
              ForwardedValues:
                QueryString: true
              SmoothStreaming: false
              ViewerProtocolPolicy: redirect-to-https
          DefaultCacheBehavior:
            Compress: true
            CachePolicyId: !Ref DefaultCachePolicy
            # https://docs.aws.amazon.com/ja_jp/AmazonCloudFront/latest/DeveloperGuide/using-managed-origin-request-policies.html
            OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf
            TargetOriginId: ${self:custom.bucketName}.s3.ap-northeast-1.amazonaws.com
            ViewerProtocolPolicy: redirect-to-https
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
          Origins:
            - Id: apiGatewayOrigin-${self:custom.stage}
              DomainName: !Join
                - "."
                - - !Ref ApiGatewayRestApi
                  - execute-api
                  - !Ref AWS::Region
                  - amazonaws.com
              OriginPath: /${self:custom.stage}
              CustomOriginConfig:
                OriginProtocolPolicy: "https-only"
            - Id: ${self:custom.bucketName}.s3.ap-northeast-1.amazonaws.com
              # If it is less than 24 hours, you need to attach a region to the resource.
              DomainName:
                # https://sls-example-test.s3-ap-northeast-1.amazonaws.com/
                sls-example-${self:custom.stage}.s3-ap-northeast-1.amazonaws.com
              # Fn::GetAtt: [StaticContentsS3, DomainName]
              S3OriginConfig:
                OriginAccessIdentity:
                  Fn::Join:
                    - '/'
                    - - origin-access-identity/cloudfront
                      - Ref: StaticCloudFrontOriginAccessIdentity
    StaticCloudFrontOriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment:
            Ref: AWS::StackName
    StaticContentsS3Policy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticContentsS3
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                AWS:
                  Fn::Join:
                    - ' '
                    - - 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity'
                      - Ref: StaticCloudFrontOriginAccessIdentity
              Action: s3:GetObject
              Resource:
                Fn::Join:
                  - '/'
                  - - Fn::GetAtt:
                        - StaticContentsS3
                        - Arn
                    - '*'
    StaticContentsS3:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: Private
        BucketName: sls-example-${self:custom.stage}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - HEAD
              AllowedOrigins:
                - '*'
    ServerlessVPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: "10.0.0.0/16"
    ServerlessSubnetA:
      DependsOn: ServerlessVPC
      Type: AWS::EC2::Subnet
      Properties:
        VpcId:
          Ref: ServerlessVPC
        AvailabilityZone: ${self:provider.region}a
        CidrBlock: "10.0.0.0/24"
    ServerlessSubnetC:
      DependsOn: ServerlessVPC
      Type: AWS::EC2::Subnet
      Properties:
        VpcId:
          Ref: ServerlessVPC
        AvailabilityZone: ${self:provider.region}c
        CidrBlock: "10.0.1.0/24"
    ServerlessSecurityGroup:
      DependsOn: ServerlessVPC
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: SecurityGroup for Serverless Functions
        VpcId:
          Ref: ServerlessVPC
    ServerlessStorageSecurityGroup:
      DependsOn: ServerlessVPC
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Ingress for Memcached Cluster & RDS Instance
        VpcId:
          Ref: ServerlessVPC
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: '5432'
            ToPort: '5432'
            SourceSecurityGroupId:
              Ref: ServerlessSecurityGroup
          - IpProtocol: tcp
            FromPort: '11211'
            ToPort: '11211'
            SourceSecurityGroupId:
              Ref: ServerlessSecurityGroup
    ServerlessRDSSubnetGroup:
      Type: AWS::RDS::DBSubnetGroup
      Properties:
        DBSubnetGroupDescription: "RDS Subnet Group"
        SubnetIds:
          - Ref: ServerlessSubnetA
          - Ref: ServerlessSubnetC
    DBInstance1:
      Type: AWS::RDS::DBInstance
      Properties:
        DBName: managed
        DBInstanceIdentifier : sls-db-${self:custom.stage}
        MasterUsername: cell
        MasterUserPassword: cellpj123
        AllocatedStorage: 20
        Engine: postgres
        EngineVersion: "11.8"
        DBInstanceClass: db.t3.medium
        VPCSecurityGroups:
          - "Fn::GetAtt": ServerlessStorageSecurityGroup.GroupId
        DBSubnetGroupName:
          Ref: ServerlessRDSSubnetGroup

  Outputs:
    CloudFrontDistribution:
      Description: atlassian distribution id.
      Value:
        Ref: CloudFrontDistribution
